/**
 * 错误代码常量
 */

// HTTP 状态码
const HTTP_STATUS = {
  OK: 200,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
  SERVICE_UNAVAILABLE: 503
};

// 错误代码
const ERROR_CODES = {
  // 通用错误
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  
  // 认证错误
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_API_KEY: 'INVALID_API_KEY',
  
  // 资源错误
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  
  // 区块链相关错误
  BLOCKCHAIN_ERROR: 'BLOCKCHAIN_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  TRANSACTION_ERROR: 'TRANSACTION_ERROR',
  CONTRACT_ERROR: 'CONTRACT_ERROR',
  
  // 合约相关错误
  CONTRACT_NOT_FOUND: 'CONTRACT_NOT_FOUND',
  CONTRACT_METHOD_NOT_FOUND: 'CONTRACT_METHOD_NOT_FOUND',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  INSUFFICIENT_FUNDS: 'INSUFFICIENT_FUNDS',
  
  // 钱包相关错误
  WALLET_ERROR: 'WALLET_ERROR',
  INVALID_PRIVATE_KEY: 'INVALID_PRIVATE_KEY',
  
  // 权限相关错误
  PERMISSION_DENIED: 'PERMISSION_DENIED'
};

// 错误消息模板
const ERROR_MESSAGES = {
  [ERROR_CODES.UNKNOWN_ERROR]: '未知错误',
  [ERROR_CODES.INTERNAL_SERVER_ERROR]: '服务器内部错误',
  [ERROR_CODES.VALIDATION_ERROR]: '验证失败',
  
  [ERROR_CODES.UNAUTHORIZED]: '未授权',
  [ERROR_CODES.INVALID_API_KEY]: '无效的API密钥',
  
  [ERROR_CODES.NOT_FOUND]: '资源不存在',
  [ERROR_CODES.ALREADY_EXISTS]: '资源已存在',
  
  [ERROR_CODES.BLOCKCHAIN_ERROR]: '区块链操作失败',
  [ERROR_CODES.NETWORK_ERROR]: '网络连接失败',
  [ERROR_CODES.TRANSACTION_ERROR]: '交易执行失败',
  [ERROR_CODES.CONTRACT_ERROR]: '合约操作失败',
  
  [ERROR_CODES.CONTRACT_NOT_FOUND]: '找不到指定的合约',
  [ERROR_CODES.CONTRACT_METHOD_NOT_FOUND]: '找不到指定的合约方法',
  [ERROR_CODES.TRANSACTION_NOT_FOUND]: '找不到指定的交易',
  [ERROR_CODES.INSUFFICIENT_FUNDS]: '余额不足',
  
  [ERROR_CODES.WALLET_ERROR]: '钱包操作失败',
  [ERROR_CODES.INVALID_PRIVATE_KEY]: '无效的私钥',
  
  [ERROR_CODES.PERMISSION_DENIED]: '权限不足'
};

module.exports = {
  HTTP_STATUS,
  ERROR_CODES,
  ERROR_MESSAGES
}; 